"""create date column again

Revision ID: 06146e7f2016
Revises: 131c513bb053
Create Date: 2023-11-03 11:39:23.122245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06146e7f2016'
down_revision = '131c513bb053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weddings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weddings', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
