"""drop date column

Revision ID: 131c513bb053
Revises: 17f05d8e3c48
Create Date: 2023-11-03 11:38:58.153774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131c513bb053'
down_revision = '17f05d8e3c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weddings', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weddings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
