"""change ownership of guests to be the user and change wedding to have a1:1 relationship using useList

Revision ID: 19a3485910ac
Revises: 658bcc3d8442
Create Date: 2023-11-17 17:27:52.896227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a3485910ac'
down_revision = '658bcc3d8442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('guests_wedding_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('wedding_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wedding_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('guests_wedding_id_fkey', 'weddings', ['wedding_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
