"""change username to email and add validation to email data column

Revision ID: 238dbf08f655
Revises: 41ba63f16d01
Create Date: 2023-08-18 13:55:03.355099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238dbf08f655'
down_revision = '41ba63f16d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
