"""try number 3

Revision ID: 43a57644a2e1
Revises: 85c4c211a20e
Create Date: 2023-11-03 11:32:25.796716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a57644a2e1'
down_revision = '85c4c211a20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
