"""add isAttending to guest model

Revision ID: 464ee5bc8362
Revises: 81ea6139c53b
Create Date: 2023-10-14 07:31:33.933501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464ee5bc8362'
down_revision = '81ea6139c53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAttending', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_column('isAttending')

    # ### end Alembic commands ###
