"""change DAteTime of wedding to s string temporarily

Revision ID: 74a703417317
Revises: fdf4554641b2
Create Date: 2023-10-06 12:55:15.608987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74a703417317'
down_revision = 'fdf4554641b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weddings', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weddings', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
