"""replace datetime default with server_now

Revision ID: 85c4c211a20e
Revises: bbb2f08eee7c
Create Date: 2023-11-03 11:21:57.689682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c4c211a20e'
down_revision = 'bbb2f08eee7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
