"""add guest model

Revision ID: fdf4554641b2
Revises: 59d0d512023e
Create Date: 2023-10-06 12:36:21.727498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf4554641b2'
down_revision = '59d0d512023e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests')
    # ### end Alembic commands ###
